### ISSUE TITLE
keras sequential module issues

### ISSUE THREAD

**Issue by sniffski** [Qengineering/TensorFlow-JetsonNano#4]
I'm facing this error when trying to run my rnn which runs well in google colab.
`Traceback (most recent call last):
  File "rnn_prediction.py", line 30, in <module>
    from keras.models import Sequential
  File "/home/***/.local/lib/python3.6/site-packages/keras/__init__.py", line 20, in <module>
    from keras import distribute
  File "/home/***/.local/lib/python3.6/site-packages/keras/distribute/__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "/home/***/.local/lib/python3.6/site-packages/keras/distribute/sidecar_evaluator.py", line 22, in <module>
    from keras.optimizers.optimizer_experimental import (
  File "/home/***/.local/lib/python3.6/site-packages/keras/optimizers/__init__.py", line 25, in <module>
    from keras import backend
  File "/home/***/.local/lib/python3.6/site-packages/keras/backend.py", line 32, in <module>
    from keras import backend_config
  File "/home/***/.local/lib/python3.6/site-packages/keras/backend_config.py", line 33, in <module>
    @tf.__internal__.dispatch.add_dispatch_support
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'dispatch'
`
Any brave ideas, how to overcome this, are much appreciated!

**Comment by Qengineering** [comment]
@sniffski ,
I'm very sorry, but I'm afraid I can't help you with this one. Once a month, for max two hours, I use python. C++ is my native tongue. Same for Google Colab and Keras. Please do note, Tensorflow version 2.5 and above (currently we have version 2.11 ) requires CUDA 11, which isn't supported by the Nano Jetpack. Could it be you facing version issues?

**Comment by sniffski** [comment]
It turned out I had to downgrade keras version to same version as tf...
